spring:
  application:
    name: cgp-account
  datasource:
#    url: jdbc:postgresql://asdf:5432/account
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: jdbc:postgresql://asdf:5432/account
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8080

management:
  observations:
    annotations:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        step: 10s
