spring:
  application:
    name: cgp-account
  # The following configuration is ignored when spring-boot-docker-compose enabled
  datasource:
    url: jdbc:postgresql://localhost:5432/account
    username: postgres
    password: postgres
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8080

management:
  observations:
    annotations:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        step: 10s
