spring:
  application:
    name: account
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: demo
    password: demo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

management:
  observations:
    annotations:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        step: 10s
